"""Built-in detection rule catalog."""

from __future__ import annotations

import re

from techspecter.sensitive_intelligence.models import FindingType, SeverityLevel
from techspecter.sensitive_intelligence.rules.models import DetectionRule, RuleCategory
from techspecter.sensitive_intelligence.rules.validators import (
    validate_aws_access_key,
    validate_github_token,
    validate_jwt_payload,
    validate_pem,
)

_SECRET_RULES: tuple[DetectionRule, ...] = (
    DetectionRule(
        rule_id="aws-access-key",
        name="AWS Access Key",
        category=RuleCategory.SECRETS,
        finding_type=FindingType.SECRET,
        subtype="aws-access-key",
        pattern=re.compile(r"AKIA[0-9A-Z]{16}"),
        severity=SeverityLevel.CRITICAL,
        confidence=97.0,
        description="AWS access key ID embedded in client-side assets.",
        recommendation="Rotate the key immediately and move secrets to a secure vault.",
        redact=True,
        validator=validate_aws_access_key,
    ),
    DetectionRule(
        rule_id="aws-secret-key",
        name="AWS Secret Key",
        category=RuleCategory.SECRETS,
        finding_type=FindingType.SECRET,
        subtype="aws-secret-key",
        pattern=re.compile(
            r"(?:aws_secret|secret_access_key)\s*[:=]\s*['\"][A-Za-z0-9/+=]{40}['\"]",
            re.I,
        ),
        severity=SeverityLevel.CRITICAL,
        confidence=96.0,
        description="AWS secret access key assignment detected.",
        recommendation=(
            "Revoke and rotate the credential; never embed AWS secrets in front-end code."
        ),
        redact=True,
    ),
    DetectionRule(
        rule_id="google-api-key",
        name="Google API Key",
        category=RuleCategory.SECRETS,
        finding_type=FindingType.SECRET,
        subtype="google-api-key",
        pattern=re.compile(r"AIza[0-9A-Za-z\-_]{35}"),
        severity=SeverityLevel.HIGH,
        confidence=96.0,
        description="Google API key exposed in a downloadable asset.",
        recommendation="Restrict the key by referrer/IP and rotate if exposed publicly.",
        redact=True,
    ),
    DetectionRule(
        rule_id="firebase-api-key",
        name="Firebase API Key",
        category=RuleCategory.SECRETS,
        finding_type=FindingType.SECRET,
        subtype="firebase-api-key",
        pattern=re.compile(r"firebase[_-]?api[_-]?key\s*[:=]\s*['\"][^'\"]{10,}['\"]", re.I),
        severity=SeverityLevel.HIGH,
        confidence=92.0,
        description="Firebase API key configuration detected.",
        recommendation="Apply Firebase security rules and restrict API key usage.",
        redact=True,
    ),
    DetectionRule(
        rule_id="stripe-secret-key",
        name="Stripe Secret Key",
        category=RuleCategory.SECRETS,
        finding_type=FindingType.SECRET,
        subtype="stripe-secret-key",
        pattern=re.compile(r"sk_(?:live|test)_[0-9a-zA-Z]{16,}"),
        severity=SeverityLevel.CRITICAL,
        confidence=97.0,
        description="Stripe secret key found in a client-accessible asset.",
        recommendation="Rotate the Stripe key and keep secret keys server-side only.",
        redact=True,
    ),
    DetectionRule(
        rule_id="github-token",
        name="GitHub Personal Access Token",
        category=RuleCategory.SECRETS,
        finding_type=FindingType.SECRET,
        subtype="github-token",
        pattern=re.compile(r"(?:ghp_|github_pat_|gho_|ghu_|ghs_|ghr_)[A-Za-z0-9_]{20,}"),
        severity=SeverityLevel.CRITICAL,
        confidence=96.0,
        description="GitHub token exposed in source material.",
        recommendation="Revoke the token in GitHub settings and use short-lived credentials.",
        redact=True,
        validator=validate_github_token,
    ),
    DetectionRule(
        rule_id="gitlab-token",
        name="GitLab Token",
        category=RuleCategory.SECRETS,
        finding_type=FindingType.SECRET,
        subtype="gitlab-token",
        pattern=re.compile(r"glpat-[A-Za-z0-9\-_]{20,}"),
        severity=SeverityLevel.CRITICAL,
        confidence=95.0,
        description="GitLab personal access token detected.",
        recommendation="Revoke the token and store credentials in a secrets manager.",
        redact=True,
    ),
    DetectionRule(
        rule_id="azure-key",
        name="Azure Key",
        category=RuleCategory.SECRETS,
        finding_type=FindingType.SECRET,
        subtype="azure-key",
        pattern=re.compile(r"(?:AccountKey|SharedAccessSignature)=[A-Za-z0-9+/=]{20,}", re.I),
        severity=SeverityLevel.CRITICAL,
        confidence=92.0,
        description="Azure storage or SAS credential detected.",
        recommendation="Rotate Azure keys and restrict access with managed identities.",
        redact=True,
    ),
    DetectionRule(
        rule_id="twilio-key",
        name="Twilio Key",
        category=RuleCategory.SECRETS,
        finding_type=FindingType.SECRET,
        subtype="twilio-key",
        pattern=re.compile(r"AC[a-f0-9]{32}"),
        severity=SeverityLevel.HIGH,
        confidence=93.0,
        description="Twilio account SID or API credential pattern detected.",
        recommendation="Verify the credential scope and rotate if exposed.",
        redact=True,
    ),
    DetectionRule(
        rule_id="slack-token",
        name="Slack Token",
        category=RuleCategory.SECRETS,
        finding_type=FindingType.SECRET,
        subtype="slack-token",
        pattern=re.compile(r"xox[baprs]-[A-Za-z0-9\-]{10,}"),
        severity=SeverityLevel.CRITICAL,
        confidence=95.0,
        description="Slack bot or user token detected.",
        recommendation="Revoke the Slack token and audit workspace access.",
        redact=True,
    ),
    DetectionRule(
        rule_id="discord-token",
        name="Discord Token",
        category=RuleCategory.SECRETS,
        finding_type=FindingType.SECRET,
        subtype="discord-token",
        pattern=re.compile(r"[MN][A-Za-z0-9]{23,}\.[A-Za-z0-9_-]{6}\.[A-Za-z0-9_-]{27}"),
        severity=SeverityLevel.CRITICAL,
        confidence=94.0,
        description="Discord bot or user token detected.",
        recommendation="Reset the Discord token immediately.",
        redact=True,
    ),
    DetectionRule(
        rule_id="openai-key",
        name="OpenAI API Key",
        category=RuleCategory.SECRETS,
        finding_type=FindingType.SECRET,
        subtype="openai-key",
        pattern=re.compile(r"sk-[A-Za-z0-9]{20,}T3BlbkFJ[A-Za-z0-9]{20,}"),
        severity=SeverityLevel.CRITICAL,
        confidence=96.0,
        description="OpenAI API key exposed in a downloadable asset.",
        recommendation="Rotate the OpenAI key and proxy requests through your backend.",
        redact=True,
    ),
    DetectionRule(
        rule_id="anthropic-key",
        name="Anthropic API Key",
        category=RuleCategory.SECRETS,
        finding_type=FindingType.SECRET,
        subtype="anthropic-key",
        pattern=re.compile(r"sk-ant-[A-Za-z0-9\-_]{20,}"),
        severity=SeverityLevel.CRITICAL,
        confidence=96.0,
        description="Anthropic API key detected.",
        recommendation="Rotate the key and keep LLM credentials server-side.",
        redact=True,
    ),
    DetectionRule(
        rule_id="jwt-token",
        name="JWT Token",
        category=RuleCategory.SECRETS,
        finding_type=FindingType.SECRET,
        subtype="jwt-token",
        pattern=re.compile(r"eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}"),
        severity=SeverityLevel.HIGH,
        confidence=94.0,
        description="JSON Web Token embedded in client-side assets.",
        recommendation="Avoid long-lived JWTs in front-end bundles; use secure httpOnly cookies.",
        redact=True,
        validator=validate_jwt_payload,
    ),
    DetectionRule(
        rule_id="bearer-token",
        name="OAuth Bearer Token",
        category=RuleCategory.SECRETS,
        finding_type=FindingType.SECRET,
        subtype="bearer-token",
        pattern=re.compile(r"Bearer\s+[A-Za-z0-9._~+/=-]{20,}", re.I),
        severity=SeverityLevel.HIGH,
        confidence=90.0,
        description="Bearer authorization token detected.",
        recommendation="Do not persist bearer tokens in client-side code or bundles.",
        redact=True,
    ),
    DetectionRule(
        rule_id="basic-auth-token",
        name="Basic Authentication Token",
        category=RuleCategory.SECRETS,
        finding_type=FindingType.SECRET,
        subtype="basic-auth-token",
        pattern=re.compile(r"Basic\s+[A-Za-z0-9+/=]{8,}", re.I),
        severity=SeverityLevel.HIGH,
        confidence=92.0,
        description="HTTP Basic authentication credential detected.",
        recommendation="Remove hardcoded basic auth credentials from source assets.",
        redact=True,
    ),
    DetectionRule(
        rule_id="session-token",
        name="Session Token",
        category=RuleCategory.SECRETS,
        finding_type=FindingType.SECRET,
        subtype="session-token",
        pattern=re.compile(r"(?:session[_-]?token|sid)\s*[:=]\s*['\"][^'\"]{16,}['\"]", re.I),
        severity=SeverityLevel.MEDIUM,
        confidence=85.0,
        description="Session token assignment detected.",
        recommendation="Store session identifiers server-side with secure cookies.",
        redact=True,
    ),
    DetectionRule(
        rule_id="generic-api-key",
        name="Generic API Key",
        category=RuleCategory.SECRETS,
        finding_type=FindingType.SECRET,
        subtype="generic-api-key",
        pattern=re.compile(
            r"(?:api[_-]?key|x-api-key)\s*[:=]\s*['\"][A-Za-z0-9_\-]{16,}['\"]", re.I
        ),
        severity=SeverityLevel.HIGH,
        confidence=88.0,
        description="Generic API key assignment detected.",
        recommendation="Move API keys to environment configuration on the server.",
        redact=True,
    ),
    DetectionRule(
        rule_id="private-key",
        name="Private Key",
        category=RuleCategory.SECRETS,
        finding_type=FindingType.SECRET,
        subtype="private-key",
        pattern=re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
        severity=SeverityLevel.CRITICAL,
        confidence=98.0,
        description="Private key material embedded in a text asset.",
        recommendation="Remove private keys from repositories and rotate affected certificates.",
        redact=True,
        validator=validate_pem,
    ),
    DetectionRule(
        rule_id="certificate",
        name="Certificate",
        category=RuleCategory.SECRETS,
        finding_type=FindingType.SECRET,
        subtype="certificate",
        pattern=re.compile(r"-----BEGIN CERTIFICATE-----"),
        severity=SeverityLevel.MEDIUM,
        confidence=85.0,
        description="X.509 certificate block detected.",
        recommendation="Verify whether the certificate should be public; remove private bundles.",
        redact=False,
        validator=validate_pem,
    ),
    DetectionRule(
        rule_id="ssh-private-key",
        name="SSH Private Key",
        category=RuleCategory.SECRETS,
        finding_type=FindingType.SECRET,
        subtype="ssh-private-key",
        pattern=re.compile(r"-----BEGIN OPENSSH PRIVATE KEY-----"),
        severity=SeverityLevel.CRITICAL,
        confidence=98.0,
        description="SSH private key detected.",
        recommendation="Revoke associated SSH access and store keys in a secure vault.",
        redact=True,
        validator=validate_pem,
    ),
    DetectionRule(
        rule_id="gcp-service-account",
        name="GCP Service Account",
        category=RuleCategory.SECRETS,
        finding_type=FindingType.SECRET,
        subtype="gcp-service-account",
        pattern=re.compile(r"\"type\"\s*:\s*\"service_account\""),
        severity=SeverityLevel.CRITICAL,
        confidence=88.0,
        description="Google Cloud service account JSON detected.",
        recommendation="Delete exposed service account keys and issue new credentials.",
        redact=False,
    ),
)

_CREDENTIAL_RULES: tuple[DetectionRule, ...] = (
    DetectionRule(
        rule_id="mongodb-uri",
        name="MongoDB Connection String",
        category=RuleCategory.CREDENTIALS,
        finding_type=FindingType.CREDENTIAL,
        subtype="mongodb-uri",
        pattern=re.compile(r"mongodb(?:\+srv)?://[^\s\"']+", re.I),
        severity=SeverityLevel.CRITICAL,
        confidence=95.0,
        description="MongoDB connection URI with embedded credentials.",
        recommendation="Rotate database credentials and restrict network access.",
        redact=True,
    ),
    DetectionRule(
        rule_id="postgresql-uri",
        name="PostgreSQL Connection String",
        category=RuleCategory.CREDENTIALS,
        finding_type=FindingType.CREDENTIAL,
        subtype="postgresql-uri",
        pattern=re.compile(r"postgres(?:ql)?://[^\s\"']+", re.I),
        severity=SeverityLevel.CRITICAL,
        confidence=95.0,
        description="PostgreSQL connection URI detected.",
        recommendation="Use managed secrets and never ship database URIs to clients.",
        redact=True,
    ),
    DetectionRule(
        rule_id="mysql-uri",
        name="MySQL Connection String",
        category=RuleCategory.CREDENTIALS,
        finding_type=FindingType.CREDENTIAL,
        subtype="mysql-uri",
        pattern=re.compile(r"mysql://[^\s\"']+", re.I),
        severity=SeverityLevel.CRITICAL,
        confidence=95.0,
        description="MySQL connection URI detected.",
        recommendation="Rotate credentials and restrict database exposure.",
        redact=True,
    ),
    DetectionRule(
        rule_id="redis-uri",
        name="Redis Connection String",
        category=RuleCategory.CREDENTIALS,
        finding_type=FindingType.CREDENTIAL,
        subtype="redis-uri",
        pattern=re.compile(r"redis://[^\s\"']+", re.I),
        severity=SeverityLevel.HIGH,
        confidence=93.0,
        description="Redis connection URI detected.",
        recommendation="Require authentication and TLS for Redis endpoints.",
        redact=True,
    ),
    DetectionRule(
        rule_id="ldap-credentials",
        name="LDAP Credentials",
        category=RuleCategory.CREDENTIALS,
        finding_type=FindingType.CREDENTIAL,
        subtype="ldap-credentials",
        pattern=re.compile(r"ldap://[^\s\"']+", re.I),
        severity=SeverityLevel.HIGH,
        confidence=90.0,
        description="LDAP connection string detected.",
        recommendation="Remove LDAP credentials from client-side assets.",
        redact=True,
    ),
    DetectionRule(
        rule_id="smtp-credentials",
        name="SMTP Credentials",
        category=RuleCategory.CREDENTIALS,
        finding_type=FindingType.CREDENTIAL,
        subtype="smtp-credentials",
        pattern=re.compile(r"smtp://[^\s\"']+", re.I),
        severity=SeverityLevel.HIGH,
        confidence=90.0,
        description="SMTP connection URI detected.",
        recommendation="Use provider-managed SMTP credentials on the server only.",
        redact=True,
    ),
    DetectionRule(
        rule_id="username-field",
        name="Hardcoded Username",
        category=RuleCategory.CREDENTIALS,
        finding_type=FindingType.CREDENTIAL,
        subtype="username-field",
        pattern=re.compile(
            r"(?:username|user_name|login|db[_-]?user|database[_-]?user)\s*[:=]\s*['\"][^'\"]{2,}['\"]",
            re.I,
        ),
        severity=SeverityLevel.MEDIUM,
        confidence=70.0,
        description="Hardcoded username assignment detected.",
        recommendation="Remove static usernames from client bundles.",
        redact=False,
    ),
    DetectionRule(
        rule_id="password-field",
        name="Hardcoded Password",
        category=RuleCategory.CREDENTIALS,
        finding_type=FindingType.CREDENTIAL,
        subtype="password-field",
        pattern=re.compile(r"(?:password|passwd|pwd)\s*[:=]\s*['\"][^'\"]{4,}['\"]", re.I),
        severity=SeverityLevel.CRITICAL,
        confidence=92.0,
        description="Hardcoded password assignment detected.",
        recommendation="Never embed passwords in source code or configuration bundles.",
        redact=True,
    ),
    DetectionRule(
        rule_id="client-id-field",
        name="OAuth Client ID",
        category=RuleCategory.CREDENTIALS,
        finding_type=FindingType.CREDENTIAL,
        subtype="client-id-field",
        pattern=re.compile(r"client[_-]?id\s*[:=]\s*['\"][^'\"]{2,}['\"]", re.I),
        severity=SeverityLevel.LOW,
        confidence=72.0,
        description="OAuth/client ID assignment detected.",
        recommendation="Client IDs are often public; ensure accompanying secrets are not exposed.",
        redact=False,
    ),
    DetectionRule(
        rule_id="client-secret-field",
        name="OAuth Client Secret",
        category=RuleCategory.CREDENTIALS,
        finding_type=FindingType.CREDENTIAL,
        subtype="client-secret-field",
        pattern=re.compile(r"client[_-]?secret\s*[:=]\s*['\"][^'\"]{8,}['\"]", re.I),
        severity=SeverityLevel.CRITICAL,
        confidence=92.0,
        description="OAuth/client secret assignment detected.",
        recommendation="Move client secrets to server-side configuration and rotate if exposed.",
        redact=True,
    ),
    DetectionRule(
        rule_id="db-user-field",
        name="Database Username",
        category=RuleCategory.CREDENTIALS,
        finding_type=FindingType.CREDENTIAL,
        subtype="db-user-field",
        pattern=re.compile(
            r"(?:db[_-]?user|database[_-]?user|db[_-]?username)\s*[:=]\s*['\"][^'\"]{2,}['\"]",
            re.I,
        ),
        severity=SeverityLevel.MEDIUM,
        confidence=75.0,
        description="Database username assignment detected.",
        recommendation="Remove database usernames from client-side assets.",
        redact=False,
    ),
    DetectionRule(
        rule_id="connection-string",
        name="Connection String",
        category=RuleCategory.CREDENTIALS,
        finding_type=FindingType.CREDENTIAL,
        subtype="connection-string",
        pattern=re.compile(
            r"(?:connection[_-]?string|conn[_-]?str|database[_-]?url|db[_-]?url)\s*[:=]\s*['\"][^'\"]+['\"]",
            re.I,
        ),
        severity=SeverityLevel.HIGH,
        confidence=90.0,
        description="Generic connection string assignment detected.",
        recommendation="Store connection strings in secure server-side configuration.",
        redact=True,
    ),
    DetectionRule(
        rule_id="api-credentials",
        name="API Credentials Block",
        category=RuleCategory.CREDENTIALS,
        finding_type=FindingType.CREDENTIAL,
        subtype="api-credentials",
        pattern=re.compile(r"(?:credentials|auth)\s*[:=]\s*\{", re.I),
        severity=SeverityLevel.MEDIUM,
        confidence=80.0,
        description="Inline credentials object detected.",
        recommendation="Review the credentials block and move secrets off the client.",
        redact=False,
    ),
)

_CONFIG_RULES: tuple[DetectionRule, ...] = (
    DetectionRule(
        rule_id="internal-api-endpoint",
        name="Internal API Endpoint",
        category=RuleCategory.SENSITIVE_CONFIGURATION,
        finding_type=FindingType.SENSITIVE_CONFIG,
        subtype="internal-api-endpoint",
        pattern=re.compile(r"['\"]/(?:api/)?(?:internal|private|admin|mgmt)[^'\"]*['\"]", re.I),
        severity=SeverityLevel.HIGH,
        confidence=82.0,
        description="Internal or administrative API endpoint referenced in client assets.",
        recommendation="Ensure internal endpoints are not exposed publicly.",
        redact=False,
    ),
    DetectionRule(
        rule_id="debug-endpoint",
        name="Debug Endpoint",
        category=RuleCategory.SENSITIVE_CONFIGURATION,
        finding_type=FindingType.SENSITIVE_CONFIG,
        subtype="debug-endpoint",
        pattern=re.compile(
            r"['\"][^'\"]*(?:/debug|/trace|/actuator|/__debug__)[^'\"]*['\"]",
            re.I,
        ),
        severity=SeverityLevel.HIGH,
        confidence=84.0,
        description="Debug or diagnostic endpoint referenced.",
        recommendation="Disable debug endpoints in production builds.",
        redact=False,
    ),
    DetectionRule(
        rule_id="staging-endpoint",
        name="Staging/Development Endpoint",
        category=RuleCategory.SENSITIVE_CONFIGURATION,
        finding_type=FindingType.SENSITIVE_CONFIG,
        subtype="staging-endpoint",
        pattern=re.compile(
            r"https?://(?:localhost|127\.0\.0\.1|[\w-]+\.(?:local|internal|staging|dev)\.[\w.-]+)"
            r"[^\s\"']*",
            re.I,
        ),
        severity=SeverityLevel.MEDIUM,
        confidence=78.0,
        description="Development or staging endpoint referenced in production assets.",
        recommendation="Remove non-production endpoints from release bundles.",
        redact=False,
    ),
    DetectionRule(
        rule_id="internal-ip",
        name="Internal IP Address",
        category=RuleCategory.SENSITIVE_CONFIGURATION,
        finding_type=FindingType.SENSITIVE_CONFIG,
        subtype="internal-ip",
        pattern=re.compile(
            r"\b(?:10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|"
            r"172\.(?:1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3})\b"
        ),
        severity=SeverityLevel.MEDIUM,
        confidence=80.0,
        description="Private RFC1918 IP address detected.",
        recommendation="Avoid exposing internal network addresses in public assets.",
        redact=False,
    ),
    DetectionRule(
        rule_id="internal-hostname",
        name="Internal Hostname",
        category=RuleCategory.SENSITIVE_CONFIGURATION,
        finding_type=FindingType.SENSITIVE_CONFIG,
        subtype="internal-hostname",
        pattern=re.compile(r"\b[\w-]+\.(?:internal|local|corp|lan)\b", re.I),
        severity=SeverityLevel.MEDIUM,
        confidence=76.0,
        description="Internal hostname reference detected.",
        recommendation="Verify whether internal hostnames should be public.",
        redact=False,
    ),
    DetectionRule(
        rule_id="db-host-field",
        name="Database Host",
        category=RuleCategory.SENSITIVE_CONFIGURATION,
        finding_type=FindingType.SENSITIVE_CONFIG,
        subtype="db-host-field",
        pattern=re.compile(
            r"(?:db[_-]?host|database[_-]?host|db[_-]?hostname)\s*[:=]\s*['\"][^'\"]{2,}['\"]",
            re.I,
        ),
        severity=SeverityLevel.MEDIUM,
        confidence=78.0,
        description="Database host configuration detected.",
        recommendation="Avoid shipping internal database hostnames to clients.",
        redact=False,
    ),
    DetectionRule(
        rule_id="feature-flag",
        name="Feature Flag",
        category=RuleCategory.SENSITIVE_CONFIGURATION,
        finding_type=FindingType.SENSITIVE_CONFIG,
        subtype="feature-flag",
        pattern=re.compile(r"(?:feature[_-]?flag|FEATURE_[A-Z0-9_]+)\s*[:=]", re.I),
        severity=SeverityLevel.LOW,
        confidence=72.0,
        description="Feature flag configuration detected.",
        recommendation="Review whether feature flags reveal unreleased functionality.",
        redact=False,
    ),
    DetectionRule(
        rule_id="environment-config",
        name="Environment Configuration",
        category=RuleCategory.SENSITIVE_CONFIGURATION,
        finding_type=FindingType.SENSITIVE_CONFIG,
        subtype="environment-config",
        pattern=re.compile(
            r"(?:process\.env|import\.meta\.env|NODE_ENV|REACT_APP_)[^\s;]{0,80}",
            re.I,
        ),
        severity=SeverityLevel.MEDIUM,
        confidence=75.0,
        description="Runtime environment configuration reference detected.",
        recommendation="Ensure build-time environment values do not leak secrets.",
        redact=False,
    ),
    DetectionRule(
        rule_id="backup-endpoint",
        name="Backup Endpoint",
        category=RuleCategory.SENSITIVE_CONFIGURATION,
        finding_type=FindingType.SENSITIVE_CONFIG,
        subtype="backup-endpoint",
        pattern=re.compile(r"['\"][^'\"]*(?:/backup|/restore|/snapshot)[^'\"]*['\"]", re.I),
        severity=SeverityLevel.MEDIUM,
        confidence=77.0,
        description="Backup or restore endpoint referenced.",
        recommendation="Restrict backup endpoints to authenticated administrative access.",
        redact=False,
    ),
)

_DEVELOPER_RULES: tuple[DetectionRule, ...] = (
    DetectionRule(
        rule_id="todo-comment",
        name="TODO Comment",
        category=RuleCategory.DEVELOPER_ARTIFACTS,
        finding_type=FindingType.COMMENT,
        subtype="todo-comment",
        pattern=re.compile(r"(?://|#|/\*|\<!--)\s*TODO\b[^\n\r]*", re.I),
        severity=SeverityLevel.INFORMATIONAL,
        confidence=70.0,
        description="TODO comment left in production assets.",
        recommendation="Review TODO items for incomplete security controls.",
        redact=False,
    ),
    DetectionRule(
        rule_id="fixme-comment",
        name="FIXME Comment",
        category=RuleCategory.DEVELOPER_ARTIFACTS,
        finding_type=FindingType.COMMENT,
        subtype="fixme-comment",
        pattern=re.compile(r"(?://|#|/\*|\<!--)\s*FIXME\b[^\n\r]*", re.I),
        severity=SeverityLevel.INFORMATIONAL,
        confidence=75.0,
        description="FIXME comment indicating unresolved issue.",
        recommendation="Resolve FIXME items before production release.",
        redact=False,
    ),
    DetectionRule(
        rule_id="hack-comment",
        name="HACK Comment",
        category=RuleCategory.DEVELOPER_ARTIFACTS,
        finding_type=FindingType.COMMENT,
        subtype="hack-comment",
        pattern=re.compile(r"(?://|#|/\*|\<!--)\s*HACK\b[^\n\r]*", re.I),
        severity=SeverityLevel.LOW,
        confidence=78.0,
        description="HACK comment indicating temporary workaround.",
        recommendation="Replace hacks with maintainable solutions.",
        redact=False,
    ),
    DetectionRule(
        rule_id="bug-comment",
        name="BUG Comment",
        category=RuleCategory.DEVELOPER_ARTIFACTS,
        finding_type=FindingType.COMMENT,
        subtype="bug-comment",
        pattern=re.compile(r"(?://|#|/\*|\<!--)\s*BUG\b[^\n\r]*", re.I),
        severity=SeverityLevel.INFORMATIONAL,
        confidence=72.0,
        description="BUG comment detected in source.",
        recommendation="Track and fix known bugs referenced in comments.",
        redact=False,
    ),
    DetectionRule(
        rule_id="note-comment",
        name="NOTE Comment",
        category=RuleCategory.DEVELOPER_ARTIFACTS,
        finding_type=FindingType.COMMENT,
        subtype="note-comment",
        pattern=re.compile(r"(?://|#|/\*|\<!--)\s*NOTE\b[^\n\r]*", re.I),
        severity=SeverityLevel.INFORMATIONAL,
        confidence=65.0,
        description="Developer NOTE comment detected.",
        recommendation="Review notes for sensitive implementation details.",
        redact=False,
    ),
    DetectionRule(
        rule_id="xxx-comment",
        name="XXX Comment",
        category=RuleCategory.DEVELOPER_ARTIFACTS,
        finding_type=FindingType.COMMENT,
        subtype="xxx-comment",
        pattern=re.compile(r"(?://|#|/\*|\<!--)\s*XXX\b[^\n\r]*", re.I),
        severity=SeverityLevel.INFORMATIONAL,
        confidence=68.0,
        description="XXX marker comment detected.",
        recommendation="Review XXX markers for security-sensitive unfinished work.",
        redact=False,
    ),
    DetectionRule(
        rule_id="stack-trace",
        name="Stack Trace",
        category=RuleCategory.DEVELOPER_ARTIFACTS,
        finding_type=FindingType.COMMENT,
        subtype="stack-trace",
        pattern=re.compile(r"(?:Traceback \(most recent call last\)|\bat\s+[\w.]+\([\w./:]+\))"),
        severity=SeverityLevel.MEDIUM,
        confidence=82.0,
        description="Stack trace or traceback snippet detected.",
        recommendation="Remove debug stack traces from production assets.",
        redact=False,
    ),
    DetectionRule(
        rule_id="debug-marker",
        name="Debug Marker",
        category=RuleCategory.DEVELOPER_ARTIFACTS,
        finding_type=FindingType.COMMENT,
        subtype="debug-marker",
        pattern=re.compile(r"\b(?:DEBUG|console\.debug|__DEBUG__)\b"),
        severity=SeverityLevel.LOW,
        confidence=76.0,
        description="Debug logging statement detected.",
        recommendation="Strip debug logging from production bundles.",
        redact=False,
    ),
    DetectionRule(
        rule_id="console-debug",
        name="Console Debug Statement",
        category=RuleCategory.DEVELOPER_ARTIFACTS,
        finding_type=FindingType.COMMENT,
        subtype="console-debug",
        pattern=re.compile(r"console\.(?:log|debug|info)\s*\("),
        severity=SeverityLevel.INFORMATIONAL,
        confidence=68.0,
        description="Console debug statement detected.",
        recommendation="Remove verbose console output from production builds.",
        redact=False,
    ),
)


def builtin_rules(*, category: RuleCategory | None = None) -> tuple[DetectionRule, ...]:
    """Return built-in detection rules, optionally filtered by category."""
    all_rules = _SECRET_RULES + _CREDENTIAL_RULES + _CONFIG_RULES + _DEVELOPER_RULES
    if category is None:
        return all_rules
    return tuple(rule for rule in all_rules if rule.category == category)
