"""Shared extraction patterns for JavaScript intelligence."""

from __future__ import annotations

import re

VERSION_CANDIDATE = re.compile(
    r"\b(?:v(?:er(?:sion)?)?[:=\s-]*)?" r"(\d{1,4}\.\d{1,4}(?:\.\d{1,4})?(?:[-+][\w.-]+)?)\b",
    re.IGNORECASE,
)
CALVER_CANDIDATE = re.compile(r"\b(20\d{2}\.\d{1,4}(?:\.\d{1,4})?)\b")
GITHUB_URL = re.compile(
    r"https?://(?:www\.)?github\.com/[\w.-]+/[\w.-]+(?:/[\w./-]*)?",
    re.IGNORECASE,
)
NPM_PACKAGE = re.compile(
    r"(?:npm(?:js)?\.com/package/(@?[\w.-]+(?:/[\w.-]+)?)|node_modules/(@?[\w.-]+(?:/[\w.-]+)?))",
    re.IGNORECASE,
)
LICENSE_HEADER = re.compile(
    r"(?:MIT|Apache(?:-2\.0)?|BSD(?:-[\d]-Clause)?|GPL(?:-[\d\.]+)?|ISC|MPL(?:-[\d\.]+)?)\s+License",
    re.IGNORECASE,
)
COPYRIGHT = re.compile(
    r"Copyright\s+(?:\(c\)|©)?\s*\d{4}(?:-\d{4})?\s+[^;\n]+",
    re.IGNORECASE,
)
GENERATED_BY = re.compile(
    r"(?:@generated|Generated by|Built with|Compiled by)\s+[^\n;]+",
    re.IGNORECASE,
)
COMMIT_HASH = re.compile(r"\b[a-f0-9]{7,40}\b")
BUILD_HASH = re.compile(r"\b(?:hash|buildId|buildHash)[\"'\s:=]+([a-f0-9]{8,64})\b", re.IGNORECASE)
