"""Build the fingerprint catalog JSON file."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

CatalogEntry = dict[str, Any]


def fp(
    id: str,
    name: str,
    category: str,
    website: str,
    description: str,
    priority: int,
    confidence: int,
    tags: list[str],
    patterns: list[dict[str, Any]],
    version_patterns: list[dict[str, Any]] | None = None,
) -> CatalogEntry:
    return {
        "id": id,
        "name": name,
        "category": category,
        "website": website,
        "description": description,
        "priority": priority,
        "confidence": confidence,
        "tags": tags,
        "patterns": patterns,
        "version_patterns": version_patterns or [],
    }


def build_catalog() -> list[CatalogEntry]:
    P = fp
    return [
        P(
            "react",
            "React",
            "framework",
            "https://react.dev",
            "JavaScript library for building user interfaces",
            100,
            85,
            ["javascript", "ui", "framework", "frontend"],
            [
                {"matcher": "filename", "pattern": "react", "weight": 20},
                {"matcher": "regex", "pattern": "__REACT_", "weight": 35},
                {"matcher": "string", "pattern": "React.createElement", "weight": 40},
                {"matcher": "global", "pattern": "React", "weight": 30},
            ],
            [
                {
                    "pattern": r'React\.version\s*=\s*["\']([0-9][0-9a-zA-Z.+-_]*)["\']',
                    "weight": 25,
                    "source": "global",
                }
            ],
        ),
        P(
            "reactdom",
            "ReactDOM",
            "framework",
            "https://react.dev",
            "React package for DOM rendering",
            95,
            82,
            ["javascript", "ui", "framework", "frontend"],
            [
                {"matcher": "filename", "pattern": "react-dom", "weight": 25},
                {"matcher": "string", "pattern": "ReactDOM.createRoot", "weight": 40},
                {"matcher": "global", "pattern": "ReactDOM", "weight": 30},
            ],
            [
                {
                    "pattern": r'ReactDOM\.version\s*=\s*["\']([0-9][0-9a-zA-Z.+-_]*)["\']',
                    "weight": 25,
                    "source": "global",
                }
            ],
        ),
        P(
            "preact",
            "Preact",
            "framework",
            "https://preactjs.com",
            "Fast 3kB React alternative",
            85,
            80,
            ["javascript", "ui", "framework", "frontend"],
            [
                {"matcher": "filename", "pattern": "preact", "weight": 25},
                {"matcher": "regex", "pattern": "__PREACT__", "weight": 35},
                {"matcher": "global", "pattern": "preact", "weight": 30},
            ],
            [{"pattern": r"preact@([0-9][0-9a-zA-Z.+-_]*)", "weight": 20, "source": "minified"}],
        ),
        P(
            "vue",
            "Vue.js",
            "framework",
            "https://vuejs.org",
            "Progressive JavaScript framework",
            95,
            85,
            ["javascript", "ui", "framework", "frontend"],
            [
                {"matcher": "filename", "pattern": "vue", "weight": 20},
                {"matcher": "string", "pattern": "Vue.createApp", "weight": 40},
                {"matcher": "global", "pattern": "Vue", "weight": 30},
            ],
            [
                {
                    "pattern": r'Vue\.version\s*=\s*["\']([0-9][0-9a-zA-Z.+-_]*)["\']',
                    "weight": 25,
                    "source": "global",
                }
            ],
        ),
        P(
            "nuxt",
            "Nuxt",
            "meta-framework",
            "https://nuxt.com",
            "Vue-based meta framework for SSR",
            95,
            85,
            ["javascript", "ssr", "framework", "frontend"],
            [
                {"matcher": "filename", "pattern": "nuxt", "weight": 25},
                {"matcher": "string", "pattern": "__NUXT__", "weight": 45},
                {"matcher": "regex", "pattern": "/_nuxt/", "weight": 30},
                {"matcher": "global", "pattern": "__NUXT__", "weight": 35},
            ],
        ),
        P(
            "angular",
            "Angular",
            "framework",
            "https://angular.dev",
            "Platform for building web applications",
            95,
            85,
            ["javascript", "ui", "framework", "frontend"],
            [
                {"matcher": "filename", "pattern": "angular", "weight": 25},
                {"matcher": "string", "pattern": "@angular/core", "weight": 35},
                {"matcher": "global", "pattern": "ng", "weight": 25},
                {"matcher": "regex", "pattern": "angular\\.module", "weight": 30},
            ],
            [
                {
                    "pattern": r"@angular/core@([0-9]+(?:\.[0-9]+){1,3})",
                    "weight": 20,
                    "source": "bundle",
                }
            ],
        ),
        P(
            "svelte",
            "Svelte",
            "framework",
            "https://svelte.dev",
            "Compiler-based UI framework",
            90,
            82,
            ["javascript", "ui", "framework", "frontend"],
            [
                {"matcher": "filename", "pattern": "svelte", "weight": 25},
                {"matcher": "string", "pattern": "SvelteComponent", "weight": 35},
                {"matcher": "regex", "pattern": "svelte/internal", "weight": 30},
            ],
            [{"pattern": r"svelte@([0-9][0-9a-zA-Z.+-_]*)", "weight": 20, "source": "minified"}],
        ),
        P(
            "solidjs",
            "SolidJS",
            "framework",
            "https://www.solidjs.com",
            "Reactive UI library",
            85,
            80,
            ["javascript", "ui", "framework", "frontend"],
            [
                {"matcher": "filename", "pattern": "solid", "weight": 20},
                {"matcher": "string", "pattern": "solid-js", "weight": 30},
                {"matcher": "string", "pattern": "createSignal", "weight": 35},
            ],
        ),
        P(
            "ember",
            "Ember.js",
            "framework",
            "https://emberjs.com",
            "Ambitious web application framework",
            80,
            78,
            ["javascript", "ui", "framework", "frontend"],
            [
                {"matcher": "filename", "pattern": "ember", "weight": 25},
                {"matcher": "string", "pattern": "Ember.Application", "weight": 35},
                {"matcher": "global", "pattern": "Ember", "weight": 30},
            ],
            [
                {
                    "pattern": r'Ember\.VERSION\s*=\s*["\']([0-9][0-9a-zA-Z.+-_]*)["\']',
                    "weight": 25,
                    "source": "global",
                }
            ],
        ),
        P(
            "backbone",
            "Backbone.js",
            "framework",
            "https://backbonejs.org",
            "Lightweight MVC framework",
            75,
            75,
            ["javascript", "ui", "framework", "frontend"],
            [
                {"matcher": "filename", "pattern": "backbone", "weight": 25},
                {"matcher": "string", "pattern": "Backbone.Model", "weight": 35},
                {"matcher": "global", "pattern": "Backbone", "weight": 30},
            ],
        ),
        P(
            "inferno",
            "Inferno",
            "framework",
            "https://infernojs.org",
            "Fast React-like library",
            75,
            75,
            ["javascript", "ui", "framework", "frontend"],
            [
                {"matcher": "filename", "pattern": "inferno", "weight": 25},
                {"matcher": "string", "pattern": "inferno/createElement", "weight": 35},
                {"matcher": "global", "pattern": "Inferno", "weight": 30},
            ],
        ),
        P(
            "astro",
            "Astro",
            "meta-framework",
            "https://astro.build",
            "Content-focused web framework",
            90,
            82,
            ["javascript", "ssr", "framework", "frontend"],
            [
                {"matcher": "filename", "pattern": "astro", "weight": 25},
                {"matcher": "string", "pattern": "astro-island", "weight": 35},
                {"matcher": "regex", "pattern": "/_astro/", "weight": 30},
            ],
        ),
        P(
            "qwik",
            "Qwik",
            "framework",
            "https://qwik.builder.io",
            "Resumable web framework",
            85,
            80,
            ["javascript", "ui", "framework", "frontend"],
            [
                {"matcher": "filename", "pattern": "qwik", "weight": 25},
                {"matcher": "string", "pattern": "@builder.io/qwik", "weight": 35},
                {"matcher": "string", "pattern": "useVisibleTask$", "weight": 30},
            ],
        ),
        P(
            "alpine",
            "Alpine.js",
            "framework",
            "https://alpinejs.dev",
            "Minimal reactive framework",
            80,
            80,
            ["javascript", "ui", "framework", "frontend"],
            [
                {"matcher": "filename", "pattern": "alpine", "weight": 25},
                {"matcher": "string", "pattern": "x-data", "weight": 30},
                {"matcher": "global", "pattern": "Alpine", "weight": 30},
            ],
        ),
        P(
            "stimulus",
            "Stimulus",
            "framework",
            "https://stimulus.hotwired.dev",
            "Modest JavaScript framework",
            75,
            75,
            ["javascript", "ui", "framework", "frontend"],
            [
                {"matcher": "filename", "pattern": "stimulus", "weight": 25},
                {"matcher": "string", "pattern": "@hotwired/stimulus", "weight": 35},
                {"matcher": "string", "pattern": "data-controller", "weight": 25},
            ],
        ),
        P(
            "lit",
            "Lit",
            "framework",
            "https://lit.dev",
            "Web components library",
            80,
            78,
            ["javascript", "ui", "framework", "frontend"],
            [
                {"matcher": "filename", "pattern": "lit", "weight": 20},
                {"matcher": "string", "pattern": "lit-element", "weight": 35},
                {"matcher": "string", "pattern": "LitElement", "weight": 30},
            ],
        ),
        P(
            "bootstrap",
            "Bootstrap",
            "css-framework",
            "https://getbootstrap.com",
            "Popular CSS framework",
            80,
            75,
            ["css", "ui", "frontend"],
            [
                {"matcher": "filename", "pattern": "bootstrap", "weight": 25},
                {"matcher": "string", "pattern": "Bootstrap", "weight": 25},
                {"matcher": "global", "pattern": "bootstrap", "weight": 20},
            ],
        ),
        P(
            "tailwindcss",
            "Tailwind CSS",
            "css-framework",
            "https://tailwindcss.com",
            "Utility-first CSS framework",
            85,
            78,
            ["css", "ui", "frontend"],
            [
                {"matcher": "filename", "pattern": "tailwind", "weight": 25},
                {"matcher": "string", "pattern": "tailwindcss", "weight": 35},
                {"matcher": "regex", "pattern": "@tailwind ", "weight": 30},
            ],
        ),
        P(
            "bulma",
            "Bulma",
            "css-framework",
            "https://bulma.io",
            "Modern CSS framework",
            70,
            72,
            ["css", "ui", "frontend"],
            [
                {"matcher": "filename", "pattern": "bulma", "weight": 25},
                {"matcher": "string", "pattern": "bulma.min.css", "weight": 30},
            ],
        ),
        P(
            "foundation",
            "Foundation",
            "css-framework",
            "https://get.foundation",
            "Responsive front-end framework",
            70,
            72,
            ["css", "ui", "frontend"],
            [
                {"matcher": "filename", "pattern": "foundation", "weight": 25},
                {"matcher": "global", "pattern": "Foundation", "weight": 30},
            ],
        ),
        P(
            "semantic-ui",
            "Semantic UI",
            "css-framework",
            "https://semantic-ui.com",
            "UI component framework",
            65,
            70,
            ["css", "ui", "frontend"],
            [
                {"matcher": "filename", "pattern": "semantic", "weight": 25},
                {"matcher": "global", "pattern": "semantic", "weight": 25},
            ],
        ),
        P(
            "material-ui",
            "Material UI",
            "css-framework",
            "https://mui.com",
            "React component library implementing Material Design",
            85,
            80,
            ["css", "ui", "frontend", "react"],
            [
                {"matcher": "filename", "pattern": "mui", "weight": 20},
                {"matcher": "string", "pattern": "@mui/material", "weight": 40},
                {"matcher": "string", "pattern": "MuiThemeProvider", "weight": 30},
            ],
        ),
        P(
            "ant-design",
            "Ant Design",
            "css-framework",
            "https://ant.design",
            "Enterprise UI design language and React library",
            85,
            80,
            ["css", "ui", "frontend", "react"],
            [
                {"matcher": "filename", "pattern": "antd", "weight": 25},
                {"matcher": "string", "pattern": "antd/lib", "weight": 30},
                {"matcher": "string", "pattern": "ant-design", "weight": 35},
            ],
        ),
        P(
            "chakra-ui",
            "Chakra UI",
            "css-framework",
            "https://chakra-ui.com",
            "Accessible React component library",
            80,
            78,
            ["css", "ui", "frontend", "react"],
            [
                {"matcher": "filename", "pattern": "chakra", "weight": 25},
                {"matcher": "string", "pattern": "@chakra-ui/react", "weight": 40},
            ],
        ),
        P(
            "uikit",
            "UIKit",
            "css-framework",
            "https://getuikit.com",
            "Lightweight front-end framework",
            70,
            72,
            ["css", "ui", "frontend"],
            [
                {"matcher": "filename", "pattern": "uikit", "weight": 25},
                {"matcher": "global", "pattern": "UIkit", "weight": 30},
            ],
        ),
        P(
            "jquery",
            "jQuery",
            "library",
            "https://jquery.com",
            "Fast, small JavaScript library",
            90,
            80,
            ["javascript", "library", "dom"],
            [
                {"matcher": "filename", "pattern": "jquery", "weight": 25},
                {"matcher": "string", "pattern": "jQuery.fn.jquery", "weight": 35},
                {"matcher": "global", "pattern": "jQuery", "weight": 30},
            ],
            [
                {
                    "pattern": r'jQuery\.fn\.jquery\s*=\s*["\']([0-9][0-9a-zA-Z.+-_]*)["\']',
                    "weight": 25,
                    "source": "global",
                }
            ],
        ),
        P(
            "lodash",
            "Lodash",
            "library",
            "https://lodash.com",
            "Modern JavaScript utility library",
            85,
            78,
            ["javascript", "library", "utility"],
            [
                {"matcher": "filename", "pattern": "lodash", "weight": 25},
                {"matcher": "string", "pattern": "_.debounce", "weight": 30},
                {"matcher": "string", "pattern": "lodash/core", "weight": 20},
            ],
        ),
        P(
            "underscore",
            "Underscore.js",
            "library",
            "https://underscorejs.org",
            "Utility-belt library for JavaScript",
            75,
            75,
            ["javascript", "library", "utility"],
            [
                {"matcher": "filename", "pattern": "underscore", "weight": 25},
                {"matcher": "string", "pattern": "_.each", "weight": 25},
            ],
        ),
        P(
            "axios",
            "Axios",
            "library",
            "https://axios-http.com",
            "Promise based HTTP client",
            85,
            80,
            ["javascript", "library", "http"],
            [
                {"matcher": "filename", "pattern": "axios", "weight": 25},
                {"matcher": "string", "pattern": "axios.create", "weight": 35},
                {"matcher": "global", "pattern": "axios", "weight": 30},
            ],
        ),
        P(
            "moment",
            "Moment.js",
            "library",
            "https://momentjs.com",
            "Date manipulation library",
            80,
            75,
            ["javascript", "library", "date"],
            [
                {"matcher": "filename", "pattern": "moment", "weight": 25},
                {"matcher": "string", "pattern": "moment().format", "weight": 30},
                {"matcher": "global", "pattern": "moment", "weight": 30},
            ],
        ),
        P(
            "dayjs",
            "Day.js",
            "library",
            "https://day.js.org",
            "Minimalist date library",
            80,
            78,
            ["javascript", "library", "date"],
            [
                {"matcher": "filename", "pattern": "dayjs", "weight": 25},
                {"matcher": "string", "pattern": "dayjs.extend", "weight": 30},
                {"matcher": "global", "pattern": "dayjs", "weight": 30},
            ],
        ),
        P(
            "rxjs",
            "RxJS",
            "library",
            "https://rxjs.dev",
            "Reactive extensions for JavaScript",
            85,
            78,
            ["javascript", "library", "reactive"],
            [
                {"matcher": "filename", "pattern": "rxjs", "weight": 25},
                {"matcher": "string", "pattern": "rxjs/operators", "weight": 35},
            ],
        ),
        P(
            "corejs",
            "core-js",
            "library",
            "https://github.com/zloirock/core-js",
            "Modular standard library for JavaScript",
            80,
            76,
            ["javascript", "library", "polyfill"],
            [
                {"matcher": "filename", "pattern": "core-js", "weight": 25},
                {"matcher": "string", "pattern": "core-js/modules", "weight": 35},
            ],
        ),
        P(
            "zonejs",
            "Zone.js",
            "library",
            "https://github.com/angular/angular/tree/main/packages/zone.js",
            "Execution context patch for Angular",
            75,
            75,
            ["javascript", "library", "angular"],
            [
                {"matcher": "filename", "pattern": "zone", "weight": 20},
                {"matcher": "string", "pattern": "Zone.__symbol__", "weight": 35},
                {"matcher": "global", "pattern": "Zone", "weight": 25},
            ],
        ),
        P(
            "hammerjs",
            "Hammer.js",
            "library",
            "https://hammerjs.github.io",
            "Touch gesture library",
            70,
            72,
            ["javascript", "library", "gesture"],
            [
                {"matcher": "filename", "pattern": "hammer", "weight": 25},
                {"matcher": "global", "pattern": "Hammer", "weight": 30},
                {"matcher": "string", "pattern": "Hammer.Manager", "weight": 30},
            ],
        ),
        P(
            "chartjs",
            "Chart.js",
            "visualization",
            "https://www.chartjs.org",
            "Simple HTML5 charts",
            85,
            80,
            ["javascript", "visualization", "chart"],
            [
                {"matcher": "filename", "pattern": "chart.js", "weight": 25},
                {"matcher": "filename", "pattern": "chart.min", "weight": 20},
                {"matcher": "string", "pattern": "Chart.register", "weight": 35},
                {"matcher": "global", "pattern": "Chart", "weight": 30},
            ],
        ),
        P(
            "d3",
            "D3.js",
            "visualization",
            "https://d3js.org",
            "Data-driven documents library",
            85,
            80,
            ["javascript", "visualization", "chart"],
            [
                {"matcher": "filename", "pattern": "d3.min", "weight": 20},
                {"matcher": "filename", "pattern": "/d3/", "weight": 15},
                {"matcher": "string", "pattern": "d3.select", "weight": 40},
                {"matcher": "global", "pattern": "d3", "weight": 30},
            ],
        ),
        P(
            "highcharts",
            "Highcharts",
            "visualization",
            "https://www.highcharts.com",
            "Interactive charting library",
            80,
            78,
            ["javascript", "visualization", "chart"],
            [
                {"matcher": "filename", "pattern": "highcharts", "weight": 25},
                {"matcher": "global", "pattern": "Highcharts", "weight": 35},
            ],
        ),
        P(
            "apexcharts",
            "ApexCharts",
            "visualization",
            "https://apexcharts.com",
            "Modern charting library",
            78,
            76,
            ["javascript", "visualization", "chart"],
            [
                {"matcher": "filename", "pattern": "apexcharts", "weight": 25},
                {"matcher": "global", "pattern": "ApexCharts", "weight": 35},
            ],
        ),
        P(
            "echarts",
            "ECharts",
            "visualization",
            "https://echarts.apache.org",
            "Powerful charting library",
            80,
            78,
            ["javascript", "visualization", "chart"],
            [
                {"matcher": "filename", "pattern": "echarts", "weight": 25},
                {"matcher": "global", "pattern": "echarts", "weight": 35},
                {"matcher": "string", "pattern": "echarts.init", "weight": 30},
            ],
        ),
        P(
            "threejs",
            "Three.js",
            "visualization",
            "https://threejs.org",
            "3D JavaScript library",
            85,
            80,
            ["javascript", "visualization", "3d"],
            [
                {"matcher": "filename", "pattern": "three", "weight": 20},
                {"matcher": "string", "pattern": "THREE.WebGLRenderer", "weight": 40},
                {"matcher": "global", "pattern": "THREE", "weight": 30},
            ],
        ),
        P(
            "pixijs",
            "PixiJS",
            "visualization",
            "https://pixijs.com",
            "2D WebGL renderer",
            78,
            76,
            ["javascript", "visualization", "2d"],
            [
                {"matcher": "filename", "pattern": "pixi", "weight": 25},
                {"matcher": "global", "pattern": "PIXI", "weight": 35},
            ],
        ),
        P(
            "leaflet",
            "Leaflet",
            "visualization",
            "https://leafletjs.com",
            "Mobile-friendly interactive maps",
            80,
            78,
            ["javascript", "visualization", "maps"],
            [
                {"matcher": "filename", "pattern": "leaflet", "weight": 25},
                {"matcher": "string", "pattern": "L.map(", "weight": 30},
                {"matcher": "global", "pattern": "L", "weight": 20},
            ],
        ),
        P(
            "openlayers",
            "OpenLayers",
            "visualization",
            "https://openlayers.org",
            "High-performance map library",
            75,
            75,
            ["javascript", "visualization", "maps"],
            [
                {"matcher": "filename", "pattern": "openlayers", "weight": 25},
                {"matcher": "string", "pattern": "ol/Map", "weight": 35},
            ],
        ),
        P(
            "mapbox-gl",
            "Mapbox GL JS",
            "visualization",
            "https://docs.mapbox.com/mapbox-gl-js",
            "Interactive vector maps",
            78,
            76,
            ["javascript", "visualization", "maps"],
            [
                {"matcher": "filename", "pattern": "mapbox-gl", "weight": 30},
                {"matcher": "global", "pattern": "mapboxgl", "weight": 35},
            ],
        ),
        P(
            "monaco",
            "Monaco Editor",
            "editor",
            "https://microsoft.github.io/monaco-editor",
            "Browser-based code editor",
            85,
            80,
            ["javascript", "editor"],
            [
                {"matcher": "filename", "pattern": "monaco", "weight": 25},
                {"matcher": "string", "pattern": "monaco-editor", "weight": 40},
                {"matcher": "global", "pattern": "monaco", "weight": 25},
            ],
        ),
        P(
            "ace",
            "Ace Editor",
            "editor",
            "https://ace.c9.io",
            "Embeddable code editor",
            80,
            78,
            ["javascript", "editor"],
            [
                {"matcher": "filename", "pattern": "ace.js", "weight": 25},
                {"matcher": "string", "pattern": "ace.edit", "weight": 35},
                {"matcher": "global", "pattern": "ace", "weight": 25},
            ],
        ),
        P(
            "codemirror",
            "CodeMirror",
            "editor",
            "https://codemirror.net",
            "Versatile text editor",
            80,
            78,
            ["javascript", "editor"],
            [
                {"matcher": "filename", "pattern": "codemirror", "weight": 25},
                {"matcher": "string", "pattern": "CodeMirror.fromTextArea", "weight": 35},
                {"matcher": "global", "pattern": "CodeMirror", "weight": 30},
            ],
        ),
        P(
            "tinymce",
            "TinyMCE",
            "editor",
            "https://www.tiny.cloud",
            "Rich text editor",
            80,
            78,
            ["javascript", "editor", "wysiwyg"],
            [
                {"matcher": "filename", "pattern": "tinymce", "weight": 25},
                {"matcher": "global", "pattern": "tinymce", "weight": 35},
            ],
        ),
        P(
            "ckeditor",
            "CKEditor",
            "editor",
            "https://ckeditor.com",
            "WYSIWYG rich text editor",
            80,
            78,
            ["javascript", "editor", "wysiwyg"],
            [
                {"matcher": "filename", "pattern": "ckeditor", "weight": 25},
                {"matcher": "global", "pattern": "CKEDITOR", "weight": 35},
            ],
        ),
        P(
            "quill",
            "Quill",
            "editor",
            "https://quilljs.com",
            "Rich text editor",
            78,
            76,
            ["javascript", "editor", "wysiwyg"],
            [
                {"matcher": "filename", "pattern": "quill", "weight": 25},
                {"matcher": "global", "pattern": "Quill", "weight": 35},
            ],
        ),
        P(
            "prism",
            "Prism.js",
            "syntax-highlighting",
            "https://prismjs.com",
            "Lightweight syntax highlighter",
            75,
            75,
            ["javascript", "syntax", "highlighting"],
            [
                {"matcher": "filename", "pattern": "prism", "weight": 25},
                {"matcher": "global", "pattern": "Prism", "weight": 35},
            ],
        ),
        P(
            "highlightjs",
            "Highlight.js",
            "syntax-highlighting",
            "https://highlightjs.org",
            "Syntax highlighting library",
            75,
            75,
            ["javascript", "syntax", "highlighting"],
            [
                {"matcher": "filename", "pattern": "highlight", "weight": 20},
                {"matcher": "global", "pattern": "hljs", "weight": 35},
            ],
        ),
        P(
            "webpack",
            "webpack",
            "build-tool",
            "https://webpack.js.org",
            "Static module bundler",
            85,
            80,
            ["javascript", "build", "bundler"],
            [
                {"matcher": "filename", "pattern": "webpack", "weight": 20},
                {"matcher": "string", "pattern": "__webpack_require__", "weight": 40},
                {"matcher": "global", "pattern": "webpackBootstrap", "weight": 30},
                {"matcher": "filename", "pattern": "chunk", "weight": 15},
            ],
        ),
        P(
            "vite",
            "Vite",
            "build-tool",
            "https://vitejs.dev",
            "Next generation frontend tooling",
            85,
            80,
            ["javascript", "build", "bundler"],
            [
                {"matcher": "filename", "pattern": "vite", "weight": 25},
                {"matcher": "string", "pattern": "import.meta.hot", "weight": 30},
                {"matcher": "global", "pattern": "viteBootstrap", "weight": 30},
            ],
        ),
        P(
            "parcel",
            "Parcel",
            "build-tool",
            "https://parceljs.org",
            "Zero configuration build tool",
            75,
            75,
            ["javascript", "build", "bundler"],
            [
                {"matcher": "filename", "pattern": "parcel", "weight": 25},
                {"matcher": "regex", "pattern": "parcelRequire", "weight": 35},
            ],
        ),
        P(
            "rollup",
            "Rollup",
            "build-tool",
            "https://rollupjs.org",
            "ES module bundler",
            75,
            75,
            ["javascript", "build", "bundler"],
            [
                {"matcher": "filename", "pattern": "rollup", "weight": 25},
                {"matcher": "string", "pattern": "rollupPlugin", "weight": 30},
            ],
        ),
        P(
            "snowpack",
            "Snowpack",
            "build-tool",
            "https://www.snowpack.dev",
            "Frontend build tool",
            70,
            72,
            ["javascript", "build", "bundler"],
            [
                {"matcher": "filename", "pattern": "snowpack", "weight": 25},
                {"matcher": "string", "pattern": "__snowpack__", "weight": 35},
            ],
        ),
        P(
            "turbopack",
            "Turbopack",
            "build-tool",
            "https://turbo.build/pack",
            "Rust-based bundler",
            75,
            75,
            ["javascript", "build", "bundler"],
            [
                {"matcher": "filename", "pattern": "turbopack", "weight": 25},
                {"matcher": "string", "pattern": "TURBOPACK", "weight": 35},
            ],
        ),
        P(
            "esbuild",
            "esbuild",
            "build-tool",
            "https://esbuild.github.io",
            "Extremely fast JavaScript bundler",
            78,
            76,
            ["javascript", "build", "bundler"],
            [
                {"matcher": "filename", "pattern": "esbuild", "weight": 25},
                {"matcher": "string", "pattern": "esbuild-wasm", "weight": 30},
            ],
        ),
        P(
            "swc",
            "SWC",
            "build-tool",
            "https://swc.rs",
            "Rust-based JavaScript compiler",
            75,
            75,
            ["javascript", "build", "compiler"],
            [
                {"matcher": "filename", "pattern": "swc", "weight": 20},
                {"matcher": "string", "pattern": "@swc/core", "weight": 35},
            ],
        ),
        P(
            "nextjs",
            "Next.js",
            "meta-framework",
            "https://nextjs.org",
            "React framework for production",
            100,
            85,
            ["javascript", "ssr", "react", "framework"],
            [
                {"matcher": "filename", "pattern": "next", "weight": 20},
                {"matcher": "string", "pattern": "__NEXT_DATA__", "weight": 45},
                {"matcher": "regex", "pattern": "/_next/static/", "weight": 30},
                {"matcher": "global", "pattern": "__NEXT_DATA__", "weight": 35},
            ],
        ),
        P(
            "remix",
            "Remix",
            "meta-framework",
            "https://remix.run",
            "Full stack React framework",
            90,
            82,
            ["javascript", "ssr", "react", "framework"],
            [
                {"matcher": "filename", "pattern": "remix", "weight": 25},
                {"matcher": "string", "pattern": "@remix-run/react", "weight": 35},
                {"matcher": "string", "pattern": "__remixContext", "weight": 35},
            ],
        ),
        P(
            "gatsby",
            "Gatsby",
            "meta-framework",
            "https://www.gatsbyjs.com",
            "React-based static site generator",
            85,
            80,
            ["javascript", "ssr", "react", "framework"],
            [
                {"matcher": "filename", "pattern": "gatsby", "weight": 25},
                {"matcher": "string", "pattern": "___loader", "weight": 30},
                {"matcher": "string", "pattern": "gatsby-browser", "weight": 30},
            ],
        ),
    ]


def main() -> None:
    catalog_path = Path(__file__).with_name("fingerprint_catalog.json")
    catalog = {"fingerprints": build_catalog()}
    catalog_path.write_text(json.dumps(catalog, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(catalog['fingerprints'])} entries to {catalog_path}")


if __name__ == "__main__":
    main()
